### PR TITLE
Create Extra

### PR DESCRIPTION
**Pull request by LehruAngela**
@CeciliaCaroline
@serubirikenny
@ruganda
@itrevex
@daud1
@Sebuliba-Adrian
@matthewacha

### CODE REVIEW

**Comment by LehruAngela** [comment]
@flacode

**Comment by ruganda** [comment]
your tests are moving in the right direction.  only that you need to add on more tests

**Comment by Sebuliba-Adrian** [comment]
The way you wrote your flask test;  you are on the right track. Just write more such tests with the test_client and restructure your code following this guide. http://www.patricksoftwareblog.com/creating-a-simple-flask-web-application/.

**Comment by LehruAngela** [comment]
@ruganda thank you very much

**Comment by LehruAngela** [comment]
@Sebuliba-Adrian thank you for the resources. I will work on this.

**Comment by itrevex** [comment]
Great work here, hope we are where you are soon enough

**Comment by CeciliaCaroline** [comment]
More descriptive commit messages
Give branches meaningful names
Comment code
Add comments to HTML
Add requirements file when working with flask and python

**Comment by LehruAngela** [comment]
@itrevex thanx for the appreciation, we'll all continue working together to achieve the tasks at hand

**Comment by LehruAngela** [comment]
@CeciliaCaroline thank you for the review. I will ensure to improve and work on the said areas.

**Comment by matthewacha** [comment]
add more comments especially with python modules. the code is organised.

**Pull request closed without merging**
